# -*- mode: yaml; coding: utf-8 -*-

include:
    - project: qs/cs.template
      ref: v15.9.0.3
      file:
          - ci/common.yml
          - ci/pre-commit.yml
          - ci/release.yml
          - ci/wheel.yml

# --------------------------------- Build stage --------------------------------
pre-commit:
    extends: .run_precommit
    needs: []

wheel:
    extends: ._wheel_base
    needs: []
    image: python:3.9
    before_script:
        - pip install build
    script:
        - python -m build -w .

# --------------------------------- Release stage --------------------------------
conpi:
    extends: ._conpi
    variables:
        PYPI_INDEX: tools/misc
    needs:
        - wheel
        - job: pre-commit # Only upload wheel when pre-commit is successful
          artifacts: false
    rules:
        - if: '$CI_COMMIT_TAG'
