# -*- mode: yaml; coding: utf-8 -*-

include:
    - project: qs/cs.template
      ref: v15.9.0.3
      file:
          - ci/common.yml
          - ci/pre-commit.yml
          - ci/wheel.yml
          - ci/release.yml
workflow:
    rules:
        - if: '$PARENT_PIPELINE_ID'
        - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != "web" && $CI_PIPELINE_SOURCE != "schedule"'
          when: never
        - when: always

# --------------------------------- Build stage --------------------------------
pre-commit:
    extends: .run_precommit
    needs: []
    rules:
        - if: '$PARENT_PIPELINE_ID'
          when: never
        - if: '$CI_COMMIT_TAG'
          when: never
        - when: on_success

wheel:
    extends: ._wheel_base
    image: python:3.9
    before_script:
        - pip install build
    needs: []
    script:
        - python -m build -w .
    rules:
        - if: '$PARENT_PIPELINE_ID'
          when: never
        - when: on_success

# --------------------------------- Test stage --------------------------------
test:
    stage: test
    image: python:3.9
    before_script:
        - pip install ".[test,spin]"
    script:
        - python -m pytest -vv tests
    needs: [wheel]
    rules:
        - if: '$PARENT_PIPELINE_ID'
          when: never
        - when: on_success

# Job gets executed by cs.spin's pipeline to download the built cs.spin wheel
# and run the integration tests against it.
triggered_integration_tests:
    stage: test
    image: python:3.9
    before_script:
        - >
            pip install cs.spin
            --index-url https://code.contact.de/api/v4/projects/1065/packages/pypi/simple
        - pip install ".[test]"
    script:
        - python -m pytest -m integration -vv tests
    needs: []
    rules:
        - if: '$PARENT_PIPELINE_ID'

# --------------------------------- Release stage --------------------------------
conpi:
    extends: ._conpi
    variables:
        PYPI_INDEX: tools/misc
    needs:
        - wheel
        - job: test
          artifacts: false
        - job: pre-commit
          artifacts: false
    rules:
        - if: '$CI_COMMIT_TAG'
